"""Rolling live-data buffer for online ROM workflows.

The live buffer receives :class:`dmdc.streaming.LiveSample` objects from a stream
adapter, validates/cleans the required state/input/time columns, and keeps a
bounded recent history.  It does **not** fit or evaluate a ROM.  This separation
is intentional: once the buffer is reliable, predictors, Kalman filters, alerts,
and dashboards can all read from the same clean interface.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import pandas as pd

from .streaming import LiveSample


@dataclass
class LiveBufferWarning:
    """Actionable warning emitted by the live buffer."""

    code: str
    message: str
    suggested_action: str
    sample_row_index: int | None = None

    def to_record(self) -> dict[str, Any]:
        return {
            "code": self.code,
            "message": self.message,
            "suggested_action": self.suggested_action,
            "sample_row_index": self.sample_row_index,
        }


@dataclass
class RollingLiveBuffer:
    """Keep recent streamed samples and provide clean state/input matrices.

    Parameters
    ----------
    state_cols, input_cols:
        Columns expected by the ROM layer.  Missing values are logged as warnings;
        invalid samples are not added to the clean buffer.
    time_col:
        Physical time column.  Live workflows assume nonuniform/adaptive time by
        default, so variable ``dt`` is summarized rather than treated as an error.
    buffer_seconds:
        Optional rolling physical-time window.  If supplied, samples older than
        ``latest_time - buffer_seconds`` are dropped from the clean buffer.
    max_samples:
        Optional maximum number of clean samples to keep.
    """

    state_cols: Sequence[str]
    input_cols: Sequence[str] = field(default_factory=list)
    time_col: str | None = None
    case_col: str | None = None
    buffer_seconds: float | None = None
    max_samples: int | None = None

    def __post_init__(self) -> None:
        self.state_cols = list(self.state_cols)
        self.input_cols = list(self.input_cols or [])
        self._raw_records: list[dict[str, Any]] = []
        self._clean_records: list[dict[str, Any]] = []
        self._warnings: list[LiveBufferWarning] = []
        self._seen_times: set[float] = set()

    @property
    def required_cols(self) -> list[str]:
        cols = list(self.state_cols) + list(self.input_cols)
        if self.time_col:
            cols.append(self.time_col)
        if self.case_col:
            cols.append(self.case_col)
        # Preserve order while dropping duplicates.
        return list(dict.fromkeys(cols))

    @property
    def raw_frame(self) -> pd.DataFrame:
        return pd.DataFrame(self._raw_records)

    @property
    def clean_frame(self) -> pd.DataFrame:
        return pd.DataFrame(self._clean_records)

    @property
    def warnings(self) -> list[LiveBufferWarning]:
        return list(self._warnings)

    def append(self, samples: Sequence[LiveSample]) -> list[LiveBufferWarning]:
        """Append samples and return warnings generated by this append call."""

        new_warnings: list[LiveBufferWarning] = []
        for sample in samples:
            raw = sample.to_record()
            self._raw_records.append(raw)
            missing = [col for col in self.required_cols if col not in sample.values]
            if missing:
                warning = LiveBufferWarning(
                    code="MISSING_REQUIRED_COLUMNS",
                    message=f"Stream sample is missing required column(s): {missing}",
                    suggested_action="Check the live logger schema or update state/input columns in the config.",
                    sample_row_index=sample.row_index,
                )
                self._warnings.append(warning)
                new_warnings.append(warning)
                continue

            clean: dict[str, Any] = {col: sample.values[col] for col in self.required_cols}
            numeric_cols = list(self.state_cols) + list(self.input_cols)
            if self.time_col:
                numeric_cols.append(self.time_col)
            invalid_numeric = []
            for col in numeric_cols:
                try:
                    clean[col] = float(clean[col])
                except (TypeError, ValueError):
                    invalid_numeric.append(col)
            if invalid_numeric:
                warning = LiveBufferWarning(
                    code="NONNUMERIC_REQUIRED_VALUE",
                    message=f"Required numeric column(s) were nonnumeric: {invalid_numeric}",
                    suggested_action="Check sensor formatting, units, and missing-value encodings.",
                    sample_row_index=sample.row_index,
                )
                self._warnings.append(warning)
                new_warnings.append(warning)
                continue
            if any(not np.isfinite(float(clean[col])) for col in numeric_cols):
                warning = LiveBufferWarning(
                    code="NONFINITE_REQUIRED_VALUE",
                    message="Required state/input/time value is NaN or infinite.",
                    suggested_action="Drop or impute this sample before using it for online prediction.",
                    sample_row_index=sample.row_index,
                )
                self._warnings.append(warning)
                new_warnings.append(warning)
                continue

            if self.time_col:
                t = float(clean[self.time_col])
                if self._clean_records:
                    last_t = float(self._clean_records[-1][self.time_col])
                    if t < last_t:
                        warning = LiveBufferWarning(
                            code="NONMONOTONIC_LIVE_TIME",
                            message=f"Received time {t} after {last_t}; clean buffer keeps arrival order.",
                            suggested_action="Check logger ordering. If late packets are expected, add a reorder window before prediction.",
                            sample_row_index=sample.row_index,
                        )
                        self._warnings.append(warning)
                        new_warnings.append(warning)
                    elif t == last_t or t in self._seen_times:
                        warning = LiveBufferWarning(
                            code="DUPLICATE_LIVE_TIME",
                            message=f"Duplicate timestamp detected: {t}.",
                            suggested_action="Check whether the logger rewrote a row or emitted a duplicate packet.",
                            sample_row_index=sample.row_index,
                        )
                        self._warnings.append(warning)
                        new_warnings.append(warning)
                self._seen_times.add(t)

            clean["_stream_source"] = sample.source
            clean["_stream_row_index"] = sample.row_index
            clean["_received_utc"] = sample.received_utc
            self._clean_records.append(clean)
        self._trim()
        return new_warnings

    def _trim(self) -> None:
        if self.max_samples is not None and self.max_samples > 0:
            if len(self._clean_records) > self.max_samples:
                self._clean_records = self._clean_records[-int(self.max_samples) :]
        if self.buffer_seconds is not None and self.time_col and self._clean_records:
            latest = float(self._clean_records[-1][self.time_col])
            cutoff = latest - float(self.buffer_seconds)
            self._clean_records = [
                rec for rec in self._clean_records if float(rec[self.time_col]) >= cutoff
            ]

    def latest_state(self) -> np.ndarray | None:
        """Return the newest clean state vector, or ``None`` if the buffer is empty."""

        if not self._clean_records:
            return None
        return np.asarray([self._clean_records[-1][col] for col in self.state_cols], dtype=float)

    def latest_input(self) -> np.ndarray | None:
        """Return the newest clean input vector, or ``None`` if there are no inputs."""

        if not self.input_cols or not self._clean_records:
            return None
        return np.asarray([self._clean_records[-1][col] for col in self.input_cols], dtype=float)

    def matrices(self) -> tuple[np.ndarray, np.ndarray, np.ndarray | None]:
        """Return ``X, U, time`` arrays from the current clean buffer."""

        frame = self.clean_frame
        if frame.empty:
            return (
                np.zeros((0, len(self.state_cols))),
                np.zeros((0, len(self.input_cols))),
                None if self.time_col is None else np.zeros(0),
            )
        X = frame[self.state_cols].to_numpy(dtype=float)
        U = frame[self.input_cols].to_numpy(dtype=float) if self.input_cols else np.zeros((len(frame), 0))
        t = frame[self.time_col].to_numpy(dtype=float) if self.time_col else None
        return X, U, t

    def summary(self) -> dict[str, Any]:
        """Summarize live-buffer status and nonuniform-time diagnostics."""

        frame = self.clean_frame
        summary: dict[str, Any] = {
            "n_raw_samples_seen": len(self._raw_records),
            "n_clean_samples_buffered": len(frame),
            "n_warnings": len(self._warnings),
            "state_cols": list(self.state_cols),
            "input_cols": list(self.input_cols),
            "time_col": self.time_col,
            "case_col": self.case_col,
            "buffer_seconds": self.buffer_seconds,
            "max_samples": self.max_samples,
        }
        if self.time_col and len(frame) >= 2:
            t = frame[self.time_col].to_numpy(dtype=float)
            dt = np.diff(t)
            summary.update(
                {
                    "time_start": float(t[0]),
                    "time_end": float(t[-1]),
                    "median_dt": float(np.median(dt)),
                    "min_dt": float(np.min(dt)),
                    "max_dt": float(np.max(dt)),
                    "dt_ratio_max_to_min": float(np.max(dt) / np.min(dt)) if np.min(dt) > 0 else float("inf"),
                    "nonuniform_time_assumed": True,
                }
            )
        return summary

    def save(self, outdir: str | Path) -> None:
        """Write raw/clean buffer logs, warnings, and summary JSON."""

        import json

        out = Path(outdir)
        out.mkdir(parents=True, exist_ok=True)
        self.raw_frame.to_csv(out / "raw_stream_log.csv", index=False)
        self.clean_frame.to_csv(out / "cleaned_stream_log.csv", index=False)
        pd.DataFrame([w.to_record() for w in self._warnings]).to_csv(out / "live_warnings.csv", index=False)
        (out / "warnings.txt").write_text(
            "\n\n".join(
                f"[{w.code}] {w.message}\nSuggested action: {w.suggested_action}"
                for w in self._warnings
            )
            or "No live-buffer warnings were emitted.\n",
            encoding="utf-8",
        )
        (out / "live_buffer_summary.json").write_text(
            json.dumps(self.summary(), indent=2), encoding="utf-8"
        )
