"""LaTeX report generation for ROM runs.

The report generator is intentionally tolerant of missing optional artifacts. It
always writes a compilable-ish ``report.tex`` with the artifacts that exist.
If a local LaTeX distribution is available, users can compile it themselves or
request ``compile_pdf=True`` from the Python API.
"""

from __future__ import annotations

from pathlib import Path
import json
import subprocess
from typing import Any

import pandas as pd


def _latex_escape(text: object) -> str:
    s = str(text)
    repl = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(repl.get(ch, ch) for ch in s)


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _include_table(path: Path, caption: str, label: str) -> str:
    if not path.exists():
        return f"\\paragraph{{{_latex_escape(caption)}}} Not available.\n"
    try:
        df = pd.read_csv(path)
        if df.empty:
            return f"\\paragraph{{{_latex_escape(caption)}}} Table exists but has no rows.\n"
        # Keep reports readable by limiting rows/columns.
        df_small = df.head(20).copy()
        if len(df_small.columns) > 8:
            df_small = df_small.iloc[:, :8]
        return df_small.to_latex(index=False, escape=True, caption=caption, label=label)
    except Exception as exc:
        return f"\\paragraph{{{_latex_escape(caption)}}} Could not render table: {_latex_escape(exc)}.\n"


def _include_figure(path: Path, caption: str, label: str) -> str:
    if not path.exists():
        return ""
    rel = path.name
    return rf"""
\begin{{figure}}[htbp]
\centering
\includegraphics[width=0.88\linewidth]{{{_latex_escape(rel)}}}
\caption{{{_latex_escape(caption)}}}
\label{{{_latex_escape(label)}}}
\end{{figure}}
"""


def generate_latex_report(run_dir: str | Path, output_tex: str | Path | None = None, *, compile_pdf: bool = False) -> Path:
    """Generate a LaTeX report from artifacts in a run directory.

    Parameters
    ----------
    run_dir:
        Directory containing outputs from ``validate``, ``compare``, ``pod-dmdc``, or similar commands.
    output_tex:
        Optional path to write the report. Defaults to ``run_dir/report/report.tex``.
    compile_pdf:
        If true, attempt to run ``pdflatex`` in the report directory. Failure is non-fatal.
    """

    run = Path(run_dir)
    report_dir = Path(output_tex).parent if output_tex is not None else run / "report"
    report_dir.mkdir(parents=True, exist_ok=True)
    output = Path(output_tex) if output_tex is not None else report_dir / "report.tex"

    # Copy nearby PDFs into the report folder so \includegraphics can use simple names.
    for fig in run.glob("*.pdf"):
        target = report_dir / fig.name
        if fig.resolve() != target.resolve():
            target.write_bytes(fig.read_bytes())
    for sub in (run / "figures", run / "dashboards").glob("*.pdf") if (run / "figures").exists() or (run / "dashboards").exists() else []:
        target = report_dir / sub.name
        target.write_bytes(sub.read_bytes())

    validation = _read_json(run / "validation_summary.json")
    stability = _read_json(run / "stability_summary.json")
    diagnostics = _read_json(run / "diagnostics.json")
    pod_summary = _read_json(run / "pod_summary.json") or _read_json(run / "pod_dmdc_summary.json")

    executive_items = []
    for name, obj in (("Validation", validation), ("Stability", stability), ("Diagnostics", diagnostics), ("POD/POD-DMDc", pod_summary)):
        if obj:
            executive_items.append(rf"\item {_latex_escape(name)} metadata found.")
    if not executive_items:
        executive_items.append(r"\item No standard JSON summaries were found; this report lists available tables and figures.")

    warning_text = ""
    for warning_file in [run / "warnings.txt", run / "stability_warnings.txt"]:
        if warning_file.exists():
            warning_text += "\n" + warning_file.read_text(encoding="utf-8")
    if not warning_text.strip():
        warning_text = "No warnings file was found."

    parts = [r"""
\documentclass[11pt]{article}
\usepackage[margin=1in]{geometry}
\usepackage{booktabs}
\usepackage{graphicx}
\usepackage{longtable}
\usepackage{hyperref}
\usepackage{float}
\title{Reduced-Order Model Analysis Report}
\author{Generated by dmdc-analysis}
\date{\today}
\begin{document}
\maketitle
\tableofcontents
\newpage
\section{Executive Summary}
\begin{itemize}
""",
    "\n".join(executive_items),
    r"""
\end{itemize}
\section{Run Directory}
""",
    f"Artifacts summarized from: \texttt{{{_latex_escape(run)}}}.\n",
    r"""
\section{Validation and Model Comparison}
""",
    _include_table(run / "validation_summary.csv", "Validation summary", "tab:validation-summary"),
    _include_table(run / "model_comparison.csv", "Model comparison", "tab:model-comparison"),
    _include_table(run / "error_by_case.csv", "Error by case", "tab:error-by-case"),
    _include_table(run / "error_by_state.csv", "Error by state", "tab:error-by-state"),
    _include_table(run / "forecast_horizon_errors.csv", "Forecast horizon errors", "tab:forecast-horizon"),
    _include_table(run / "sweep_results.csv", "Sweep results", "tab:sweep-results"),
    _include_table(run / "best_models.csv", "Best sweep candidates", "tab:best-sweep-models"),
    _include_table(run / "selected_sensors.csv", "Selected POD sensors", "tab:selected-sensors"),
    _include_table(run / "sparse_sensor_reconstruction_error.csv", "Sparse sensor reconstruction error", "tab:sparse-sensor-error"),
    _include_table(run / "operating_condition_summary.csv", "Train/test operating-condition summary", "tab:operating-conditions"),
    _include_table(run / "uncertainty_summary.csv", "Bootstrap uncertainty summary", "tab:uncertainty"),
    _include_table(run / "case_quality_dashboard.csv", "Case quality dashboard", "tab:case-quality"),
    r"""
\section{Stability Diagnostics}
""",
    _include_table(run / "eigenvalues.csv", "Eigenvalues", "tab:eigenvalues"),
    _include_table(run / "stability_dashboard.csv", "Stability dashboard", "tab:stability-dashboard"),
    r"""
\section{Figures}
""",
    _include_figure(report_dir / "model_comparison.pdf", "Train/test rollout error comparison.", "fig:model-comparison"),
    _include_figure(report_dir / "forecast_error_vs_horizon.pdf", "Forecast error versus horizon.", "fig:forecast-horizon"),
    _include_figure(report_dir / "eigenvalues_complex_plane.pdf", "Eigenvalues in the complex plane.", "fig:eigenvalues"),
    _include_figure(report_dir / "error_by_case.pdf", "Rollout error by case.", "fig:error-by-case"),
    _include_figure(report_dir / "rank_vs_error.pdf", "Sweep error versus rank candidates.", "fig:rank-vs-error"),
    _include_figure(report_dir / "delay_vs_error.pdf", "Sweep error versus delay candidates.", "fig:delay-vs-error"),
    _include_figure(report_dir / "stability_vs_error.pdf", "Sweep stability versus held-out error.", "fig:stability-vs-error"),
    _include_figure(report_dir / "reconstruction_error_vs_sensors.pdf", "Sparse POD reconstruction error versus selected sensors.", "fig:sensors-error"),
    _include_figure(report_dir / "pod_modes_vs_geometry.pdf", "POD mode amplitudes versus loop position.", "fig:pod-modes-geometry"),
    _include_figure(report_dir / "error_vs_geometry.pdf", "Prediction error versus loop position.", "fig:error-geometry"),
    _include_figure(report_dir / "selected_sensors_geometry.pdf", "Selected sensors along loop geometry.", "fig:selected-sensors-geometry"),
    r"""
\section{Best Model Recommendation}
\begin{verbatim}
""",
    ((run / "best_model_recommendation.txt").read_text(encoding="utf-8") if (run / "best_model_recommendation.txt").exists() else "No recommendation file found."),
    r"""
\end{verbatim}
\section{Warnings and Suggested Actions}
\begin{verbatim}
""",
    warning_text[:12000],
    r"""
\end{verbatim}
\section{Reproducibility Notes}
This report is generated from saved CSV, JSON, and PDF artifacts. If a table or figure is missing, rerun the corresponding workflow with plotting enabled.
\end{document}
""",
    ]
    output.write_text("\n".join(parts), encoding="utf-8")

    if compile_pdf:
        try:
            subprocess.run(["pdflatex", "-interaction=nonstopmode", output.name], cwd=output.parent, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        except FileNotFoundError:
            (output.parent / "latex_compile_warning.txt").write_text("pdflatex was not found. Compile report.tex manually if desired.\n", encoding="utf-8")
    return output
